;; Packages
(use-package auto-complete
  :ensure t)
(use-package autopair
  :ensure t)
(use-package elscreen-persist
  :ensure t)
(use-package elscreen
  :ensure t)
(use-package exec-path-from-shell
  :ensure t)
(use-package helm
  :ensure t)
(use-package helm-ag
  :ensure t)
(use-package helm-projectile
  :ensure t)
(use-package expand-region
  :ensure t)
(use-package js2-mode
  :ensure t)
(use-package multiple-cursors
  :ensure t)
(use-package projectile
  :ensure t)
(use-package virtualenvwrapper
  :ensure t)
(use-package rfringe
  :ensure t)
(use-package enh-ruby-mode
  :ensure t)
(use-package slime
  :ensure t)
(use-package ac-slime
  :ensure t)
(use-package yasnippet
  :ensure t)
(use-package web-mode
  :ensure t)
(use-package magit
  :ensure t)
(use-package eww
  :ensure t)
(use-package python-mode
  :ensure t)
(use-package jedi
  :ensure t)
(use-package go-mode
  :ensure t)
(use-package go-guru
  :ensure t)
(use-package go-autocomplete
  :ensure t)
(use-package gore-mode
  :ensure t)
(use-package yaml-mode
  :ensure t)
(use-package magit-gerrit
  :ensure t)

;; Themes
(use-package zenburn-theme
  :ensure t)
(use-package base16-theme
  :ensure t)
