;; Packages
(use-package auto-complete
  :ensure t)
(use-package autopair
  :ensure t)
(use-package elscreen-persist
  :ensure t)
(use-package elscreen
  :ensure t)
(use-package exec-path-from-shell
  :ensure t)
(use-package helm
  :ensure t)
(use-package helm-ag
  :ensure t)
(use-package helm-projectile
  :ensure t)
(use-package expand-region
  :ensure t)
(use-package js2-mode
  :ensure t)
(use-package multiple-cursors
  :ensure t)
(use-package projectile
  :ensure t)
(use-package virtualenvwrapper
  :ensure t)
(use-package enh-ruby-mode
  :ensure t)
(use-package slime
  :ensure t)
(use-package ac-slime
  :ensure t)
(use-package yasnippet
  :ensure t)
(use-package web-mode
  :ensure t)
(use-package magit
  :ensure t)
(use-package eww
  :ensure t)
(use-package python-mode
  :ensure t)
(use-package go-mode
  :ensure t)
(use-package go-guru
  :ensure t)
(use-package gorepl-mode
  :ensure t)
(use-package yaml-mode
  :ensure t)
(use-package cmake-mode
  :ensure t )
(use-package flycheck
  :ensure t)
(use-package cmake-ide
  :ensure t)
(use-package jedi-core
  :ensure t)
(use-package company-jedi
  :ensure t)
(use-package company
  :ensure t)
(use-package company-go
  :ensure t)
(use-package groovy-mode
  :ensure t)
(use-package rjsx-mode
  :ensure t)
(use-package json-mode
  :ensure t)
(use-package skewer-mode
  :ensure t)
(use-package js2-refactor
  :ensure t)
(use-package xref-js2
  :ensure t)
(use-package helm-xref
  :ensure t)
(use-package docker-tramp
  :ensure t)
(use-package docker
  :ensure t)
(use-package magit-gerrit
  :ensure t)
(use-package import-js
  :ensure t)
(use-package nginx-mode
  :ensure t)
(use-package company-nginx
  :ensure t)

;; Themes
(use-package zenburn-theme
  :ensure t)
(use-package base16-theme
  :ensure t)
