;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        about-emacs
        autopair-insert-opening
        backward-sexp
        beginning-of-defun
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-semi&comma
        c-indent-line-or-region
        comment-dwim
        compile
        dabbrev-expand
        erlang-electric-comma
        erlang-electric-gt
        erlang-electric-semicolon
        forward-sexp
        indent-for-tab-command
        kill-region
        mark-sexp
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        paredit-forward-delete
        paredit-forward-kill-word
        split-line
        wgrep-finish-edit
        yas-abort-snippet
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        autopair-skip-close-maybe
        helm-M-x
        mac-mwheel-scroll
        org-self-insert-command
        ))
