((docker-image-help nil)
 (docker-image-ls
  ("--all")
  ("--filter reference='aelwa_eng*'")
  ("--filter before=aelwa")
  ("--filterbefore=aelwa")
  ("--filter image=aelwa_eng")
  ("--filter name=aelwa_eng")
  ("--filtername=aelwa_eng")
  ("--filteraelwa_eng"))
 (docker-image-rm nil
                  ("-f"))
 (forge-dispatch nil)
 (magit-am
  ("--3way"))
 (magit-blame
  ("-w"))
 (magit-branch nil)
 (magit-cherry-pick
  ("--ff"))
 (magit-commit nil)
 (magit-diff
  ("--no-ext-diff" "--stat")
  (("--" "src/aepublish_ae_client.erl"))
  (("--" "src/aetag_api.erl"))
  (("--" "tests/test_lwa_host_probe_tagset.py"))
  (("--" "./"))
  (("--" "etc/lwa_demo-env.template"))
  (("--" "cfn/base.yaml")
   "-U10")
  ("-U30" "--no-ext-diff" "--stat")
  (("--" "etc/aesessions_user-env.template"))
  (("--" "etc/aeshard_demo-env.template")))
 (magit-diff:-U "10" "30")
 (magit-dispatch nil)
 (magit-ediff nil)
 (magit-fetch nil)
 (magit-gitignore nil)
 (magit-log
  (("--" "cfn/ae-lwas.yaml"))
  ("-n256" "--graph" "--decorate")
  (("--" "./"))
  (("--" "roam/20230718151613-grind75.org")
   "--graph")
  (("--" "roam/20230718151613-grind75.org"))
  (("--" "test/aecontent_live_SUITE.erl"))
  (("--" "src/aepublish_ae_client.erl"))
  (("--" "etc/lwa_publish_metrics-env.template"))
  (("--" "test/aefr_SUITE.erl"))
  (("--" "aetuner/server/get_analytic.py")))
 (magit-merge nil)
 (magit-pull
  ("--rebase"))
 (magit-push
  ("--force-with-lease")
  ("--force")
  ("--force-with-lease" "--force")
  ("--dry-run"))
 (magit-rebase nil)
 (magit-remote
  ("-f"))
 (magit-reset nil)
 (magit-revert
  ("--edit"))
 (magit-run nil)
 (magit-stash nil)
 (magit-submodule nil)
 (magit-tag nil
            ("--annotate"))
 (magit:-- "cfn/base.json")
 (transient:docker-image-ls:--filter " reference='aelwa_eng*'" " before=aelwa" "before=aelwa" " image=aelwa_eng" " name=aelwa_eng" "--filter name=aelwa_eng" "name=aelwa_eng" "aelwa_eng"))
