((docker-image-help nil)
 (docker-image-ls
  ("--all")
  ("--filter reference='aelwa_eng*'")
  ("--filter before=aelwa")
  ("--filterbefore=aelwa")
  ("--filter image=aelwa_eng")
  ("--filter name=aelwa_eng")
  ("--filtername=aelwa_eng")
  ("--filteraelwa_eng"))
 (docker-image-rm nil
                  ("-f"))
 (forge-dispatch nil)
 (magit-am
  ("--3way"))
 (magit-blame
  ("-w"))
 (magit-branch nil)
 (magit-cherry-pick
  ("--ff"))
 (magit-commit nil)
 (magit-diff
  (("--" "src/aetag_api.erl"))
  ("--no-ext-diff" "--stat")
  (("--" "tests/test_lwa_host_probe_tagset.py"))
  (("--" "./"))
  (("--" "etc/lwa_demo-env.template"))
  (("--" "cfn/base.yaml")
   "-U10")
  ("-U30" "--no-ext-diff" "--stat")
  (("--" "etc/aesessions_user-env.template"))
  (("--" "etc/aeshard_demo-env.template"))
  (("--" "cfn/ae-engines.yaml")
   "-U30" "--function-context"))
 (magit-diff:-U "10" "30")
 (magit-dispatch nil)
 (magit-ediff nil)
 (magit-fetch nil)
 (magit-gitignore nil)
 (magit-log
  (("--" "src/aefr_eng_config.erl"))
  (("--" "aetuner/server/update_analytic.py"))
  (("--" "config/aesolo.config"))
  (("--" "src/aefr_eng.erl"))
  (("--" "etc/aerta-env.template"))
  (("--" "src/aetrigger_eng.hrl"))
  (("--" "src/aetrigger_eng.erl"))
  (("--" "src/aefr_eng_metrics_srv.erl"))
  (("--" "./"))
  (("--" "src/aetrigger_eng_publish.erl")))
 (magit-merge nil)
 (magit-pull
  ("--rebase"))
 (magit-push
  ("--force-with-lease")
  ("--force")
  ("--force-with-lease" "--force")
  ("--dry-run"))
 (magit-rebase nil)
 (magit-reset nil)
 (magit-revert
  ("--edit"))
 (magit-run nil)
 (magit-stash nil)
 (magit-submodule nil)
 (magit-tag nil
            ("--annotate"))
 (magit:-- "cfn/base.json")
 (transient:docker-image-ls:--filter " reference='aelwa_eng*'" " before=aelwa" "before=aelwa" " image=aelwa_eng" " name=aelwa_eng" "--filter name=aelwa_eng" "name=aelwa_eng" "aelwa_eng"))
